filepath: ""
helmfiles:
- path: helmfiles/backend-devops/helmfile.yaml
- path: helmfiles/jenkins-for-jx/helmfile.yaml
- path: helmfiles/jx-staging/helmfile.yaml
- path: helmfiles/jx/helmfile.yaml
- path: helmfiles/tekton-pipelines/helmfile.yaml
- path: helmfiles/jx-production/helmfile.yaml
templates: {}
renderedvalues: {}
