# Source: jenkins-resources/templates/tekton-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-tekton-pipelines
  namespace: jenkins-for-jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
rules:
  - apiGroups:
      - tekton.dev
    resources:
      - "*"
    verbs:
      - list
      - get
      - watch
      - create
      - update
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - list
      - get
      - watch
