# Source: jenkins-resources/templates/maven-settings-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-maven-settings
  namespace: jenkins-for-jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: local
  data:
    - name: settings.xml
      key: settings.xml
      property: settings.xml
    - name: settings-security.xml
      key: settings-security.xml
      property: settings-security.xml
  template:
    type: Opaque
