apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        vindhya-mora/ang-jx: true
        vindhya-mora/angular-jx: true
        vindhya-mora/angular-jx-jan28: true
        vindhya-mora/jenkins-jx: true
        vindhya-mora/jx-angular: true
        vindhya-mora/jx3-openshift: true
        vindhya-mora/python-31stjan: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: false
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        vindhya-mora/ang-jx: merge
        vindhya-mora/angular-jx: merge
        vindhya-mora/angular-jx-jan28: merge
        vindhya-mora/jenkins-jx: merge
        vindhya-mora/jx-angular: merge
        vindhya-mora/jx3-openshift: merge
        vindhya-mora/python-31stjan: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - vindhya-mora/jx3-openshift
        - vindhya-mora/ang-jx
        - vindhya-mora/angular-jx-jan28
        - vindhya-mora/angular-jx
        - vindhya-mora/jenkins-jx
        - vindhya-mora/jx-angular
        - vindhya-mora/python-31stjan
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - vindhya-mora/jx3-openshift
        - vindhya-mora/ang-jx
        - vindhya-mora/angular-jx-jan28
        - vindhya-mora/angular-jx
        - vindhya-mora/jenkins-jx
        - vindhya-mora/jx-angular
        - vindhya-mora/python-31stjan
      target_url: http://dashboard-jx.devopsnextgenlatestdal13-f3fc6b3f137d049465f1eda82e10db30-0000.us-south.containers.appdomain.cloud
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
