apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  labels:
    name: backend-devops
    gitops.jenkins-x.io/pipeline: 'cluster'
    team: 'jx'
  name: backend-devops
spec: {}
status: {}
