apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SourceConfig
metadata:
  creationTimestamp: null
spec:
  groups:
  - owner: vindhya-mora
    provider: https://github.com
    providerKind: github
    repositories:
    - name: ang-jx
    - name: angular-jx
    - name: angular-jx-jan28
    - name: jenkins-jx
    - name: jx-angular
    scheduler: in-repo
  jenkinsServers:
  - groups:
    - owner: vindhya-mora
      provider: https://github.com
      providerKind: github
      repositories:
      - name: springboot-31stjan
    server: devops
